### ISSUE TITLE
Manifest uploading error causes operation halt

### ISSUE THREAD

**Issue by ORBAT** [ORBAT/S4QS-RS#11]
Exceptions while uploading manifests cause the whole pipe to stop, since if manifest uploading fails, no new SQS messages will be fetched etc.

```
Tue, 02 Jun 2015 17:31:40 GMT s4qs-rs:manifest:error Error uploading manifest s3://somepathhere: 500: null
Unhandled rejection 500: null
    at Request.extractError (/usr/lib/node_modules/s4qs-rs/node_modules/aws-sdk/lib/services/s3.js:328:35)
    at Request.callListeners (/usr/lib/node_modules/s4qs-rs/node_modules/aws-sdk/lib/sequential_executor.js:100:18)
    at Request.emit (/usr/lib/node_modules/s4qs-rs/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/usr/lib/node_modules/s4qs-rs/node_modules/aws-sdk/lib/request.js:592:14)
    at Request.transition (/usr/lib/node_modules/s4qs-rs/node_modules/aws-sdk/lib/request.js:21:12)
    at AcceptorStateMachine.runTo (/usr/lib/node_modules/s4qs-rs/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /usr/lib/node_modules/s4qs-rs/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/usr/lib/node_modules/s4qs-rs/node_modules/aws-sdk/lib/request.js:22:9)
    at Request.<anonymous> (/usr/lib/node_modules/s4qs-rs/node_modules/aws-sdk/lib/request.js:594:12)
    at Request.callListeners (/usr/lib/node_modules/s4qs-rs/node_modules/aws-sdk/lib/sequential_executor.js:104:18)
    at Request.emit (/usr/lib/node_modules/s4qs-rs/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/usr/lib/node_modules/s4qs-rs/node_modules/aws-sdk/lib/request.js:592:14)
    at Request.transition (/usr/lib/node_modules/s4qs-rs/node_modules/aws-sdk/lib/request.js:21:12)
    at AcceptorStateMachine.runTo (/usr/lib/node_modules/s4qs-rs/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /usr/lib/node_modules/s4qs-rs/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/usr/lib/node_modules/s4qs-rs/node_modules/aws-sdk/lib/request.js:22:9)
```

**Comment by ORBAT** [comment]
The upcoming 1.0.4 version bails out on manifest upload errors
